bazel-contrib/rules_oci

- WORKSPACE
- container/private/toolchains_repo.bzl
- container/private/versions.bzl
- container/repositories.bzl
- scripts/filter.jq
- scripts/mirror_releases.sh
Adds support for platforms other than MacOS
> Mirror release info into versions file

- .bazelrc
- .github/workflows/ci.bazelrc
- cosign/toolchain.bzl
- example/attach/BUILD.bazel
- example/attach/test.bash
- example/push/BUILD.bazel
- example/push/test.bash
- example/sign/BUILD.bazel
- example/sign/test.bash
- oci/dependencies.bzl
- oci/private/BUILD.bazel
- oci/private/image.bzl
- oci/private/image.sh.tpl
- oci/private/image_index.bzl
- oci/private/image_index.sh.tpl
- oci/private/push.bzl
- oci/private/structure_test.bzl
- oci/private/tarball.bzl
- oci/private/tarball.sh.tpl
- oci/private/zot_launcher.sh.tpl
- oci/repositories.bzl
- oci/toolchain.bzl
closes #41 and disabled legacy external runfiles
> refactor: cleanup toolchains

- README.md
- docs/image.md
- e2e/wasm/BUILD.bazel
- e2e/wasm/WORKSPACE
- e2e/wasm/main.rs
- oci/private/image.bzl
Demonstrating wasm container images via rules_rust
> docs: add example for wasm containers

- oci/pull.bzl
This value seems to be written by the newer crane version when running pull
Fixes #108
> chore: fix red CI

- .bcr/presubmit.yml
- .github/workflows/ci.yaml
- README.md
- e2e/crane_as_registry/.bazelrc
- e2e/crane_as_registry/BUILD.bazel
- e2e/crane_as_registry/MODULE.bazel
- e2e/crane_as_registry/WORKSPACE.bazel
- e2e/crane_as_registry/WORKSPACE.bzlmod
- e2e/crane_as_registry/test.yaml
> chore: add e2e test for crane as registry

- docs/pull.md
- e2e/custom_registry/BUILD.bazel
- e2e/custom_registry/WORKSPACE
- oci/BUILD.bazel
- oci/pull.bzl
> feat: implement auth for oci_pull

- .bcr/presubmit.yml
I've had to manually patch the last couple BCR releases with this change
> chore: no windows test yet

- WORKSPACE
- oci/pull.bzl
- oci/tests/BUILD.bazel
fixes #134. consequently fixes #127
> fix: pulling from public ecr

- oci/pull.bzl
> fix: DOCKER_CONFIG is a dir not file

- oci/private/image.sh.tpl
This is an attempt to resolve #68. 
Error wording could be better, but the framework is there 😄
> fix: print an actionable warning when INVALID_MANIFEST encountered

- MODULE.bazel
- oci/private/auth_config_locator.bzl
Sorry! I forgot to remove this. was put there to debug the absence case. Fortunately, #131 is adding tests that catch this.
> fix: auth_config_locator incorrectly reports presence

- docs/BUILD.bazel
- docs/image.md
- examples/labels/BUILD.bazel
- examples/labels/test.yaml
- oci/defs.bzl
- oci/private/image.bzl
- oci/private/image.sh.tpl
> feat: allow stamping labels/annotations

- docs/structure_test.md
- e2e/crane_as_registry/BUILD.bazel
- e2e/custom_registry/BUILD.bazel
- e2e/smoke/BUILD.bazel
- examples/empty_base/BUILD.bazel
- examples/env_inheritance/BUILD.bazel
- examples/labels/BUILD.bazel
- oci/private/structure_test.bzl
> refactor: rename structure_test#config -> configs

- docs/cpp.md
- docs/go.md
- docs/groovy.md
- docs/java.md
- docs/javascript.md
- docs/python.md
- docs/rust.md
- docs/scala.md
Fixes #55
(I'll go ping people to solicit contributions, but not gating 1.0 on that)
> docs: add placeholders for more languages

- fetch.bzl
- oci/private/pull.bzl
- oci/tests/BUILD.bazel
> fix: fallback to curl on manifest fetch error

- docs/tarball.md
- oci/defs.bzl
- oci/private/tarball.bzl
- oci/private/tarball.sh.tpl
> feat: Allow stampable repotags for oci_tarball

- fetch.bzl
> fix: remove duplicate debian target

- oci/private/push.sh.tpl
Reverts bazel-contrib/rules_oci#208
> Revert "fix: extract image digest raw from yq"

- examples/env_inheritance/BUILD.bazel
- examples/multi_arch/BUILD.bazel
> test: assert oci_* rules are reproducible

- cosign/private/versions.bzl
This adds the two latest releases of cosign to `COSIGN_VERSIONS`
> add latest cosign releases

- docs/image.md
- docs/push.md
- oci/defs.bzl
Fixes #233
Preview: https://github.com/bazel-contrib/rules_oci/blob/6753dab2bb7496f615793b8bddef166d34da34d6/docs/image.md
> docs: add load site

- .github/workflows/release_prep.sh
- docs/image_index.md
- oci/private/image_index.bzl
- oci/private/util.bzl
> Replace shasum with sha256sum

- docs/static_content.md
- docs/tarball.md
- e2e/wasm/BUILD.bazel
- oci/private/BUILD.bazel
- oci/private/tarball.bzl
- oci/private/tarball_run.sh.tpl
> feat: #180 make the tarball target runnable

- oci/private/BUILD.bazel
- oci/private/image.bzl
- oci/private/tarball.bzl
- oci/private/util.bzl
This allows us to invoke our bash program under windows, otherwise you get the usual CreateProcess error %1 is not a valid win32 application
> feat(windows): introduce batch wrapper

- examples/empty_base/BUILD.bazel
- oci/private/tarball.sh.tpl
> fix(windows): account for \r\n line endings

- oci/private/image.bzl
> fix(windows): prevent path transformation of arguments to crane mutate

- docs/pull.md
- oci/extensions.bzl
- oci/private/pull.bzl
- oci/pull.bzl
> fix(bzlmod): print working MODULE.bazel reproducibility instructions

- docs/go.md
- docs/rust.md
- docs/static_content.md
- e2e/wasm/BUILD.bazel
- examples/env/BUILD.bazel
- examples/env_inheritance/BUILD.bazel
- examples/labels/BUILD.bazel
- examples/multi_arch/BUILD.bazel
- examples/sign/BUILD.bazel
@rules_pkg//pkg.bzl => @rules_pkg//pkg:tar.bzl
> load pkg_tar from the right location

- oci/private/download.bzl
> fix: report curl stderr when return_code non-zero

- docs/image.md
- examples/location_expansion/BUILD.bazel
- examples/location_expansion/test.bash
- examples/location_expansion/test.yaml
- oci/defs.bzl
- oci/private/image.bzl
- oci/private/image.sh.tpl
> feat: make cmd and environment attributes stampable

- oci/private/tarball.sh.tpl
Replacement for https://github.com/bazel-contrib/rules_oci/pull/298
Closes https://github.com/bazel-contrib/rules_oci/issues/280
> Fix invalid tarball manifest creation

- docs/push.md
- oci/private/push.bzl
> docs: oci_push authorization

- oci/private/pull.bzl
> refactor: make download_manifest return digest

- oci/private/tarball.sh.tpl
Currently blocking the release. https://buildkite.com/bazel/bcr-presubmit/builds/2504#018bcfd2-00a7-4345-b427-0aa80e8b8f61/319-347
> fix: tarball unbound variable error if zero tags provided

- oci/private/download.bzl
> chore: remove unused header dump

- oci/private/registry/crane_launcher.sh.tpl
- oci/private/registry/zot_launcher.sh.tpl
fixes https://github.com/bazel-contrib/rules_oci/issues/418
> fix: listen on loopback address

- oci/private/image.sh.tpl
The contents of the stderr file is now printed in case or error (script used to fail silently).
> fix: improve error handling in image.sh.tpl

- fetch.bzl
- oci/private/pull.bzl
- oci/tests/BUILD.bazel
add docker.elastic.co registry support
Based on https://github.com/bazel-contrib/rules_oci/issues/463
> add docker.elastic.co registry support

- oci/private/push.sh.tpl
> fix: unbound variable error

- docs/compare_dockerfile.md
Asked by a customer, putting it up as a doc for future reference.
https://github.com/bazel-contrib/rules_oci/issues/35
> docs: comparison to dockerfile

- .bcr/presubmit.yml
Merge bazel-contrib/rules-template#105
> chore: add bazel matrix

- examples/big_image/BUILD.bazel
Adding a big image example to mimic what AI people do to create container images.
> example: add a big image example

- oci/private/download.bzl
- oci/private/pull.bzl
Reduces the surface area for bugs subtle caching bugs. The curl callback is only for manifests and only for a subset of manifests and these are very small files either way. The callback will be removed in 2.0 since a change in Bazel 7 will make it unecessary.
> fix: remove curl cache

- oci/private/image.bzl
> image: allow .tar.zst extension on layer tar

- oci/private/image.sh
fixes https://github.com/bazel-contrib/rules_oci/issues/473
now oci_image has no system dependency other than bash.
> fix: make oci_image fully hermetic

- oci/pull.bzl
> feat: Allow setting both tag and digest in oci_pull when reproducible is True

- README.md
Per Bazel Slack discussion, add a link to ociupdate and a new "3rd Party Extensions/Tools" section to the README.
> Mention ociupdate in the README

- oci/private/authn.bzl
Fixed by partial back-porting of #618 by @thesayyn.
I'm unsure how to test this without backporting the entirety of https://github.com/bazel-contrib/rules_oci/commit/9f0079bd88474a66957f7aa77d751226b7876884, which can't be cherry-picked cleanly.
> fix: Fix unconditional use of credsStore (#653)

- .gitattributes
- .github/workflows/ci.yaml
- oci/private/push.sh.tpl
See: https://github.com/bazelbuild/bazel-central-registry/pull/2563#issuecomment-2310972670
> fix: include examples

- MODULE.bazel
- WORKSPACE
- docs/load.md
- docs/push.md
- examples/push/BUILD.bazel
- internal_deps.bzl
- oci/private/load.bzl
- oci/private/push.bzl
We get this question a lot so the answer belongs in the docs.
> chore(docs): mention rules_multirun

- oci/repositories.bzl
> fix: declare and register regctl toolchains only for compatible platforms

- e2e/assertion/BUILD.bazel
Green up main before we get red PRs that aren't the authors fault
> chore(ci): disable two failing tests

- .github/workflows/release_prep.sh
Automation failed this morning https://github.com/bazel-contrib/rules_oci/actions/runs/12299290847/job/34324766219
> chore: fix tag name when called by workflow

- cosign/repositories.bzl
- oci/BUILD.bazel
- oci/repositories.bzl
See https://github.com/bazelbuild/bazel-skylib/issues/568
> fix: correct bzl_library targets
