bazel-contrib/rules_oci

.github/workflows/ci.yaml
.github/workflows/release.yml

@thesayyn 
Github actions caches don't update already existing caches, so the cache that gets loaded could be old. This sets a new cache using a cache key derived from a hash of files. The use of restore-keys: bazel-cache- will find the most recent cache stored scoped to this branch or a parent branch.

build: fix ci build caching

---

.github/workflows/ci.bazelrc
.github/workflows/ci.yaml
.github/workflows/release.yml

@thesayyn Some more fixes to ci build cacheing. See the rules-template changes here: https://github.com/bazel-contrib/rules-template/pull/4
Apparently bazelrc doesn't recognize environment variables.

fix: move cache flags out of ci bazelrc

---

.github/workflows/ci.bazelrc
.github/workflows/ci.yaml
.github/workflows/release.yml

Sorry to keep changing this, but we've settled on putting the cache flags in bazelrc in rules-template since we realized that it supports `~` paths. Feel free to keep or close as this doesn't change anything functionally.

build: move ci cache flags to bazelrc

---

.github/workflows/ci.yaml

This fixes paths to caches for Bazel in CI, in the same way aspect-build/rules_js#366 fixed.

Fix paths to caches for Bazel in CI

---

docs/BUILD.bazel
docs/push.md
example/push/BUILD.bazel
example/push/test.bash
oci/defs.bzl
oci/private/BUILD.bazel
oci/private/push.bzl
oci/private/push.sh.tpl

feat: implement oci_push

---

cosign/private/sign.bzl
docs/cosign_sign.md
docs/push.md
oci/private/push.bzl

This needs to be in backticks to prevent downstream rendering crashes

chore(docs): fix bad html tag appearing in markdown

---

docs/image.md
oci/private/image.bzl

This PR fixes a typo in the example of `oci_image` rule.

Fix typo in example of `oci_image`

---

.github/workflows/ci.yaml

Currently, GitHub Actions caches on macOS are not uploaded because the key is shared between Ubuntu and macOS and, because CI in Ubuntu normally finishes much earlier (See screenshot of macOS build below). This prevents Bazel on macOS from fully taking advantage of GitHub Actions caches. (macOS runner always downloads caches built by the Ubuntu runner, but those caches are not always usable for macOS such as Go object files)
This PR allows to use cache keys per OS so that caches can be used on macOS.

Cache results per OS

---

internal_deps.bzl

This PR fixes the URL to download bazel-skylib. Currently, we get the warning something like:
```shell
$ bazel test //example/js:test
...
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/1.1.1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```
The correct form should be
`https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/<VERSION>/bazel-skylib-
<VERSION>.tar.gz`
where `VERSION` is a version number.
(ref: https://github.com/bazelbuild/bazel-skylib/releases/tag/1.1.1)

fix: url to download bazel-skylib

---

docs/image.md
examples/labels/BUILD.bazel
examples/labels/test.bash
examples/labels/test.yaml
oci/private/image.bzl
oci/tests/BUILD.bazel

Fixes https://github.com/bazel-contrib/rules_oci/issues/47
I would like to have stamping support before merging this PR. I see @alexeagle is working on stamping in https://github.com/bazel-contrib/rules_oci/pull/70.
From what I understand, the script that builds the image will need to read the volatile and stable files when stamping is enabled, and do variable substitution for each key (if found). Should I try something like https://github.com/aspect-build/bazel-lib/blob/998ee223690ed07b3dfc31738dae839206bd60b0/lib/tests/stamping/stamper.sh ? Or is there a more native alternative for stamping?

Add labels to oci_image

---

.github/workflows/release_prep.sh

*Changes*
GitHub Release Workflow has the incorrect location for the `rules_oci_dependencies` rule. Changed `.github/workflows/release_prep.sh` from:
```
load("@contrib_rules_oci//oci:repositories.bzl", "rules_oci_dependencies")
```
to
```
load("@contrib_rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")
```

FIX: Github Workflows Release template

---

docs/BUILD.bazel
docs/push.md
examples/push/BUILD.bazel
examples/push/stamp_tags.bzl
oci/BUILD.bazel
oci/defs.bzl
oci/private/push.bzl
oci/private/push.sh.tpl

stamping for tags

---

e2e/wasm/WORKSPACE
e2e/wasm/main.rs

Small fix. 
Rust does not have a 2022 edition. It's current editions are 2015, 2018 and 2021.
See: https://doc.rust-lang.org/edition-guide/

fix: rust does not have a 2022 edition

---

.prettierignore
docs/structure_test.md
e2e/smoke/BUILD.bazel
e2e/smoke/WORKSPACE.bazel
oci/private/structure_test.bzl
oci/private/tarball.bzl

This allows many tests to run on a platform with no container runtime, like the BCR presubmit

feat: support the driver argument of container-test

---

e2e/smoke/.bazelrc

It seems to be broken on BCR windows presubmit:
https://buildkite.com/bazel/bcr-presubmit/builds/1117#0186d6d0-96a6-44c8-8176-93c67cfdebac
```
File c:bbk-windows-58ckbazelbcr-presubmitbcr_presubmit.py, line 240, in prepare_test_module_repo
scratch_file(test_module_root, .bazelrc, [
File c:bbk-windows-58ckbazelbcr-presubmitbcr_presubmit.py, line 147, in scratch_file
with open(abspath, mode) as f:
OSError: [Errno 22] Invalid argument: 'c:\b\bk-windows-58ck\bazel-downstream-projects\output\rules_oci-0.3.4\e2e\smoke\.bazelrc'
```

chore: don't use symlink for e2e bazelrc

---

oci/repositories.bzl

It's defined here: https://github.com/bazel-contrib/rules_oci/blob/main/oci/private/versions.bzl#L35
Fixes #97

fix: structure test platform keys include .exe suffix on windows

---

MODULE.bazel
oci/private/versions.bzl
scripts/mirror_releases.sh

```
% bazel run @oci_crane_darwin_arm64//:crane -- version
0.14.0
```
Unblocks us removing the custom registry for examples
Thanks @imjasonh

chore: mirror new crane version

---

oci/private/toolchains_repo.bzl
oci/repositories.bzl
oci/tests/BUILD.bazel

Allows us to use `repo_utils.platform` and matches our other repositories.

refactor: rename x86_64 to amd64

---

MODULE.bazel
oci/extensions.bzl
oci/pull.bzl

However it trips over the labels in our generated build files making assumptions about repository names, needs some fixing

chore(bzlmod): add trivial pass-through module extension for oci_pull

---

docs/pull.md

#118 merged due to that race condition, where a PR marked for auto-merge is temporarily green after a new commit is pushed and the new github actions yellow status isn't created yet.

chore: update docs

---

oci/dependencies.bzl
oci/pull.bzl

This PR is composed of two commits:
1. Fixes a bug in `rules_pkg`'s sha256
2. Fixes #74. Adds support for OCI media types. Currently, `pull` only supports the media types from the docker standard, but it should also support the media types from the OCI standard.
Relevant specs:
* [Docker standard](https://github.com/distribution/distribution/blob/main/docs/spec/manifest-v2-2.md#media-types
) (already supported)
* [OCI standard](https://github.com/opencontainers/image-spec/blob/main/media-types.md) (support added in this PR)
Error this PR is fixing:
Setup:
```
bazel_dep(name = "aspect_bazel_lib", version = "1.29.2")
bazel_dep(name = "platforms", version = "0.0.5")
bazel_dep(name = "rules_oci", version = "0.3.8")
bazel_dep(name = "rules_pkg", version = "0.8.1")
oci = …
```

Support OCI media types on pull in addition to docker media types

---

oci/tests/BUILD.bazel

Otherwise it only passes when the host arch is amd64
Fixes #160
Now `bazel test //...` is green on my M1 Mac

fix: transition a test to explicit arch

---

docs/push.md
examples/push/BUILD.bazel
examples/push/test.bash
oci/private/push.bzl
oci/private/push.sh.tpl

refactor: merge repository into repotags

---

MODULE.bazel
oci/dependencies.bzl

can't use [0.9.0](https://github.com/bazelbuild/rules_pkg/releases/tag/0.9.0): broken digest
can't downgrade to [0.8.1](https://github.com/bazelbuild/rules_pkg/releases/tag/0.8.1):  compatibility level

fix: downgrade rules_pkg to 0.7.0

---

docs/rust.md

Hi guys, 
I'm using `rules_oci` and see that Rust build instructions is missing. 
So I  create this PR to add build instruction & a small example for Rust.

docs: add build instruction for rust

---

oci/private/tarball.sh.tpl

The current tarball.sh.tpl script is generating a manifest.json file which formats the repotags as a string. 
Example:
```
[
{
"Config": "blobs/sha256/81e06113ed0b517fd70e4933d505b5f29a117e13edc50b5bba81af88c8f0effb",
"RepoTags": "phono:latest",
"Layers": [
"blobs/sha256/6b0b1527d75b1e49c2cb08f4eb8616c64c9a20a8b9d8c1179146b2675586536b.tar.gz",
"blobs/sha256/26e3e4b0848c0e87391a7a844b11fcd2e6d223bd516be6ac8b17bac4e6808609.tar.gz",
"blobs/sha256/6670ae47b92addccf12843ef586edfbd7764c5d360e2ddc4a64e035625ce4bb9.tar.gz"
]
}
]
```
But Docker attempts to parse the manifest with an array of strings for the repotags, resulting in this error:
```
json: cannot unmarshal string into Go struct field manifestItem.RepoTags of type []string
```
This PR updates the bash script to format the repo tags as …

Fix bug with formatting of repotags in tarball manifest.json [re-do]

---

oci/private/push.sh.tpl

`yq` will quote the digest string, which will break image pushing.
For example:
```
INFO: Elapsed time: 1.673s, Critical Path: 1.12s
INFO: 5 processes: 1 internal, 4 darwin-sandbox.
INFO: Build completed successfully, 5 total actions
INFO: Running command line: bazel-bin/backend/api/cmd/push_push.sh
europe-west1-docker.pkg.dev/xx/xx
21:48:51 initCommand [WARN] JSON file output is now JSON by default (instead of yaml). Use '-oy' or '--output-format=yaml' for yaml output
Error: could not parse reference: xxxxxx@"sha256:ca70bd1e4c8fada66c93f31c58019ad72dc1f7a6d5a7fa900127e817c87ae679"
```
Remove the warning and unwrap the string.

fix: extract image digest raw from yq

---

docs/push.md
e2e/auth/BUILD.bazel
e2e/auth/test.bats
examples/push/BUILD.bazel
examples/push/test.bash
oci/private/push.bzl
oci/private/push.sh.tpl

We decided the new API is significantly harder to use, and less intuitive.
This reverts commit 85b695c9b953c3a96d46c116e8fa7af3026588f1.

Revert "refactor: merge repository into repotags (#169)"

---

examples/push/BUILD.bazel
oci/BUILD.bazel
oci/private/BUILD.bazel
oci/private/pull.bzl
oci/private/push.bzl
oci/private/util.bzl
oci/pull.bzl
oci/tests/pull_tests.bzl

fix: port number should be allowed in push

---

docs/push.md
e2e/auth/BUILD.bazel
examples/push/BUILD.bazel
examples/push/stamp_tags.bzl
oci/defs.bzl
oci/private/push.bzl

Having `repotags` in both oci_push and oci_tarball is confusing for the users given they have different semantics.

refactor: rename repotags to default_tags

---

docs/tarball.md
e2e/crane_as_registry/BUILD.bazel
e2e/smoke/BUILD.bazel
e2e/wasm/BUILD.bazel
examples/empty_base/BUILD.bazel
oci/defs.bzl
oci/private/tarball.bzl
oci/private/tarball.sh.tpl

This reflects the CamelCase -> snake_case mapping, since the term in the manifest.json is 'RepoTags'

chore: rename repotags to repo_tags

---

.bazelversion
.github/workflows/ci.yaml
README.md
oci/private/pull.bzl

Bazel 6.2.0 contains a fix for https://github.com/bazelbuild/bazel/issues/17655
Fixes #230

chore: remove bzlmod workaround

---

oci/private/pull.bzl

Tested using `cgr.dev` (Chainguard Images), which configures per-domain credHelpers for authentication.
Update: This appears to be nearly identical to what was proposed in #236 - I'd be happy for either to be merged.

fix: implement per registry credential helpers

---

fetch.bzl
oci/private/pull.bzl
oci/tests/BUILD.bazel

Obsoletes #238 
The Chainguard Images registry (cgr.dev) require a temporary token to be acquired for authentication. Without adding `cgr.dev` to `_WWW_AUTH`, the test fails with:
```log
WARNING: Download from https://cgr.dev/v2/chainguard/static/manifests/latest failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 401 Unauthorized
ERROR: An error occurred during the fetch of repository 'chainguard_static':
Traceback (most recent call last):
File "/home/t/src/rules_oci/oci/private/pull.bzl", line 477, column 51, in _oci_alias_impl
manifest, _ = downloader.download_manifest(rctx.attr.identifier, "mf.json")
File "/home/t/src/rules_oci/oci/private/pull.bzl", line 280, column 74, in lambda
download_manifest = lambda identifier, …
```

Add auth support for cgr.dev (Chainguard Images)

---

oci/private/pull.bzl
oci/private/tarball.sh.tpl

There is no guarantee that the OCI Manifest layers record contains only unique items. For example, layers which contain no change in the docker image FS will always have a same digests. In such a case, `bazel` will complain that `srcs` for `blog` target contains duplicities. Therefore, we need to be sure that there is no such duplicities when creating `tars` list.
Example of error message:
```
ERROR: /beyond/.bazel_cache/external/test_image_single/BUILD.bazel:43:18: Label '@test_image//:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1' is duplicated in the 'srcs' attribute of rule 'blobs'
```

Make sure that the `tars` list contains unique records

---

oci/tests/BUILD.bazel

When executed on M1 mac, the diff was failing, as we were comparing alias pointing to ARM (default local platform) vs. crane fetched hardcoded amd.
```
40a3355584e3c9359179972071a/sandbox/darwin-sandbox/208/execroot/rules_oci/bazel-out/darwin_arm64-fastbuild/bin/oci/tests/test_chainguard_static-test.sh.runfiles/chainguard_static_linux_arm64/layout/index.json
8c8
<          "digest": "sha256:fbfb8a6a1edd7e4f714a3bfdd5e5446e0c13af472d629714399e0c3354db2619",
---
>          "digest": "sha256:bbb40acafe3392a2ff85fa23f597caad80ced4ec698f1adc7638f4fb806d78b2",
10c10
<             "architecture": "amd64",
---
>             "architecture": "arm64",
FAIL: directories "oci/tests/chainguard_static" and "external/chainguard_static_linux_arm64/layout" differ.
```

Fix failing //oci/tests:test_chainguard_static test on ARM.

---

oci/private/versions.bzl

Add latest version [v0.15.2](https://github.com/google/go-containerregistry/releases/tag/v0.15.2) of `crane`.

Update Crane version

---

oci/private/download.bzl

Fixes #183 
The initial idea was to just replace curl with a script that does this check, something akin to https://stackoverflow.com/a/22508743. It seems much easier to just test the output in Starlark, since we have all the required information on-hand.

Replace --fail-with-body for a test that checks the status code

---

oci/private/download.bzl

This is as simple fix for #284. It may not solve the root cause, which I do not know what that might be, but it appears to resolve #284.

Fix: Error: key "type" not found in dictionary

---

oci/private/tarball.sh.tpl

Fix for this issue: https://github.com/bazel-contrib/rules_oci/issues/273
New version of "yq" will fail processing a path that includes '"'. This fix removes the extra '"' from the path in MANIFEST_DIGEST in the script template that creates the tarball.

Remove '"' from path in MANIFEST_DIGEST when creating a tar file

---

oci/private/image_index.sh.tpl

Output directories (`ctx.actions.declare_directory` et al) are created by bazel
before invoking the action.  On 'clever' build executors, they may be symlinks
to other locations or other exotic implementation details.
A naive `mkdir -p` will try to create these directories if they don't exist _and
also_ set dir permissions to what mkdir thinks they should be.  This latter
permissions step can fail in more interesting build environments, even when the
dir already exists and `mkdir -p` should be a no-op.
This PR avoids invoking `mkdir -p` at all if the dir already exists.

fix: Avoid mkdir -p attempting to change permissions

---

docs/push.md
oci/private/push.bzl

I don't believe `tags` is a valid parameter name: https://github.com/bazel-contrib/rules_oci/blob/main/oci/defs.bzl#L62
It also doesn't seem to be a valid parameter of `oci_push_rule`.

Fix typo in oci_push docs

---

docs/tarball.md
oci/private/tarball.bzl

We always tried to read from the file, so this isn't a breaking change - it already wouldn't have worked
Fixes #272

fix(docs): indicate that oci_tarball#repo_tags is mandatory

---

examples/empty_base/BUILD.bazel
oci/private/tarball.sh.tpl

Due to usage of 'replace_one' in bash instead of 'replace_all',
the attempts to run `bazel run examples/empty_base/tarball` (with 3 tags), failed with 'Invalid reference format' error, as the line 2 and 3 kept being separated by 'explicit \n'.

fix: oci_tarball should support more than 2 repo_tags

---

oci/private/BUILD.bazel
oci/private/auth_config_locator.bzl

It now has a windows-aware logic to return HOMEPATH instead.
Note, I'm not bumping the minimal bazel-lib version here, but Windows users will have to upgrade it to get the fix.

fix(windows): use bazel-lib helper to read HOME env var

---

examples/repo_tags/BUILD.bazel
examples/repo_tags/tags_file.txt
examples/repo_tags/test.yaml
oci/private/tarball.bzl
oci/private/tarball.sh.tpl

In particular without the change, a file with a trailing '\n' in the last line (expected) was considered to generate a new empty repo-tag.

Ignore empty repo-tags in the file. Allow \n at the end of files.

---

examples/deb/BUILD.bazel
oci/private/image.bzl

See explanation in #302. Non-tar files never actually worked here.
Fixes #302

fix: restrict oci_image#tar attribute to .tar files

---

oci/private/pull.bzl

The way auth is currently splitting username:password does not work if the password contains colons(:). Such is the case when authenticating against the Google Artifact Registry using a Service Account.  Allowing a maximum of 1 splits will make it work.

fix: allow passwords that contain  :

---

.github/workflows/release_prep.sh
README.md

We should include an oci.pull, otherwise that's hard to find

docs: improve bzlmod install instructions

---

examples/deb/BUILD.bazel
oci/private/image.bzl

Partial revert of #313 which went too far in trimming the allow_files extensions.
Fixes #334

fix(oci_image): restore tars=foo.tar.gz

---

docs/image.md
docs/push.md
oci/defs.bzl
oci/private/download.bzl

Tags were not being propagated to targets declared by the macros in `defs.bzl`. This fixes that by using [propagate_well_known_tags](https://github.com/aspect-build/bazel-lib/blob/main/docs/utils.md#propagate_well_known_tags) to propagate a relevant subset of tags to all targets.

fix: propagate tags for macros in `defs.bzl`

---

oci/defs.bzl

Hashes should generally be prefixed with the hash algorithm used. Also, the intent of adding .digest in #346 was to make the migration from rules_docker easier, so we should match its output, as shown https://github.com/bazelbuild/rules_docker/blob/master/tests/container/BUILD#L248-L251
Note, this is not a breaking change, because the commit from #346 was not yet released.

fix: digest output should include algo

---

docs/push.md
examples/push/BUILD.bazel
examples/push/repository.txt
examples/push/test.bash
oci/private/push.bzl
oci/private/push.sh.tpl

As mentioned in the updated docs this is useful if you want to push to a different repository (eg, separate dev/prod repositories) based on a stamp variable.

Allow passing repository for oci_push in from a file

---

oci/pull.bzl

fix(pull): reproducible attribute of oci_pull macro was unused.

---

oci/private/pull.bzl

* update how `_WWW_AUTH` is used to match registry
* use placeholder `{registry}` in field `realm` and `service`
* also check for suffix match
* update how authentication response is handled
* check for field `access_token` 
* fail if no token found

feat: add Azure Container Registry oci_pull support

---

oci/private/image.bzl

This argument is not providing a useful purpose and breaks when oci_image targets have a capital letter in their name. Removing this does not break the image build since the ref used between the mutate and pull is sourced directly from the output of crane
Closes #351 
Within the image.sh script, this slightly changes the value of the `$REF` variable used from the initial mutate call. Prior to this change, these look like:
`127.0.0.1:42477/<target name>@sha256:<some sha hash>`
Now these inherit the source name for the mutation and look like:
`127.0.0.1:42477/oci/layout@sha256:<some sha hash>` or `127.0.0.1:42477/oci/empty_base@sha256:<some sha hash>`
If you would prefer, the alternate fix is to use a static sentinel value for tag (e.g. `--tag oci:registry/target`), which produces refs like …

fix: remove tag argument from crane image mutate call

---

oci/private/image_index.sh.tpl

https://github.com/bazel-contrib/rules_oci/issues/358

feat: use link instead of copy for blobs in oci_image_index

---

fetch.bzl
oci/private/pull.bzl
oci/tests/BUILD.bazel

This adds www-authenticate information for registry.gitlab.com.

feat: add Gitlab Container Registry oci_pull support

---

docs/image.md
docs/push.md
oci/defs.bzl

In trying to fix tag propagation, #350 broke tag propagation behavior for some targets which did have tags forwarded properly. The reason the behavior changed is because while we are still propagating tags in #350, we started passing them through [propagate_well_known_tags](https://github.com/aspect-build/bazel-lib/blob/main/docs/utils.md#propagate_well_known_tags) which caused some issues, e.g. https://github.com/bazel-contrib/rules_oci/pull/350#issuecomment-1724530364.
This restores the old behavior for the targets which did have tags propagated, while also propagating all tags for the new targets.

fix: Propagate all tags, not just well known ones

---

oci/private/pull.bzl
oci/private/util.bzl
oci/tests/BUILD.bazel

fix: add variant to manifest entry 

---

oci/private/pull.bzl

Now when there is no matching platform in oci_alias, users will see an error with list of available platforms from the image. 
```
alias(
name = "chainguard_static",
actual = select(
{
"@platforms//cpu:x86_64": "@chainguard_static_linux_amd64", 
"@platforms//cpu:arm64": "@chainguard_static_linux_arm64", 
"@platforms//cpu:ppc": "@chainguard_static_linux_ppc64le", 
"@platforms//cpu:s390x": "@chainguard_static_linux_s390x"
},
no_match_error = """could not find an image matching the target platform. \navailable platforms are "linux/386", "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64", "linux/ppc64le", "linux/s390x" """,
),
visibility = ["//visibility:public"],
)
```
fixes #178

feat: add custom no_match_error to oci_alias

---

oci/private/tarball.sh.tpl

This way we can generate reproducible tars and avoid sha256sums changing for the tar output of the oci_tarball rule.

oci_tarball: fix file time to 2000-01-01 for files inside the tar

---

oci/private/tarball.sh.tpl

Reverts bazel-contrib/rules_oci#380
It broke MacOS CI (only on main build sadly)

Revert "oci_tarball: set mtime to 2000-01-01"

---

MODULE.bazel
docs/image.md
docs/push.md
oci/defs.bzl
oci/dependencies.bzl

As per #369, trying to put a test in an `oci_image` target by making it `testonly = True` is currently broken.
This PR just adds the common rule attribute`testonly` to the `oci_image` and `oci_tarball` macros and forwards its value along to all the rules they instantiate.

fix: forward well known attributes to macro expanded targets

---

.github/workflows/ci.yaml

We need at least some coverage, even if we don't have a container runtime there

chore: enable some CI on macos again

---

MODULE.bazel
WORKSPACE
docs/image.md
docs/image_index.md
docs/pull.md
docs/push.md
docs/tarball.md
internal_deps.bzl
oci/defs.bzl
oci/dependencies.bzl

Picked this up from  #370. We needed to update stardoc in the workspace to match the bazel-lib bzlmod stardoc version so that outputs are identical.

fix: forward well known attributes to macro expanded targets (#370)

---

oci/private/pull.bzl

This adds www-authenticate information for .app.snowflake.com.
As these registries are private I can't add tests for it.
The one space removed at the end of the line is the buildifier job...

feat: add Snowflake's registries support for oci_pull

---

oci/private/tarball.sh.tpl

Rather than doing a bunch of replacements, use bash builtins of array parsing and array stringifying.

refactor: simplify repotags processing

---

docs/tarball.md
examples/multi_arch_go/BUILD
examples/multi_arch_go/main.go
oci/private/tarball.bzl
oci/private/tarball.sh.tpl

Support tar files for multi-arch images

---

docs/go.md
docs/rust.md

If I understand correctly, `architecture` and `os` cannot be specified when using a base image. It appears that rust and go documentation are outdated. This PR attempts to fix this discrepancy.

fix: fixed go and rust doc 

---

oci/private/registry/crane_launcher.sh.tpl

So that no blobs are left over at /tmp. bazel automatically discards undeclared outputs, which will make the cleanup out of band for performance reasons. With #324 we will make use storage dir for further performance improvement.

fix: make crane use storage directory

---

oci/private/image.sh.tpl
oci/private/registry/zot_launcher.sh.tpl
oci/private/versions.bzl
oci/repositories.bzl
scripts/mirror_releases_zot.sh

Updates zot to the latest release and switches to minimal binaries for smaller and faster builds.

refactor: update zot and use minimal binaries

---

docs/image.md
e2e/crane_as_registry/BUILD.bazel
e2e/crane_as_registry/MODULE.bazel
oci/defs.bzl
oci/private/image.bzl
oci/private/image.sh.tpl

feat: add exposed_ports to oci_image

---

MODULE.bazel
oci/private/BUILD.bazel
oci/private/image.bzl
oci/private/util.bzl
oci/private/versions.bzl
oci/repositories.bzl
oci/toolchain.bzl

bumps crane version to `0.17.0` and introduces a check to prevent confusing messages

feat: bump and assert crane version

---

docs/rust.md

It took me quite a bit of time to figure out how to fix compatibility issues with binaries compiled with newer glibc. Including a specific example of oci_pull with a newer debian cc image should help future wanderers.

Provide an example in the compatibility section

---

e2e/convert_docker_tarball/convert.bash
e2e/custom_registry/registry/launcher.sh
oci/private/image.sh.tpl
oci/private/registry/crane_launcher.sh.tpl
oci/private/registry/zot_launcher.sh.tpl
oci/toolchain.bzl

crane / zot launcher: kill registry serve process on shell exit

---

e2e/custom_registry/registry/launcher.sh
oci/private/registry/crane_launcher.sh.tpl
oci/private/registry/zot_launcher.sh.tpl

Follow-up for #421.
I noticed that those messages are always printed, even on success. Theoretically, there is a choice between printing those messages to stdout instead, silencing stderr on success or dropping the message.
The last option is the easiest.

fix: do not print message to stderr during normal operation

---

oci/private/toolchains_repo.bzl

Now that Bazel 7.0 has been released, it's time to remove this tech debt.
This has been a no-op since Bazel 5.0, I've been waiting to remove the code for two years, it's time.
Part of https://github.com/bazelbuild/bazel/issues/14127.

Remove uses of `incompatible_use_toolchain_transition`.

---

MODULE.bazel
oci/dependencies.bzl
oci/private/pull.bzl

Require a newer aspect_bazel_lib, to pick up a fix for execution requirements - something about build-without-the-bytes causes the directory to be missing file contents.
Fixes #425

chore: bump minimum bazel-lib

---

oci/private/pull.bzl

Bazel doesn't really support source directories and prints an annoying warning when one lists a source directory as dependency.
fixes #448

fix: glob blobs directory

---

docs/tarball.md
oci/private/tarball.bzl
oci/private/tarball_run.sh.tpl

Enables passing a label to `oci_tarball` which will be used to load the image into the local container engine.
Solves https://github.com/bazel-contrib/rules_oci/issues/295
Follows guidance from https://github.com/bazel-contrib/rules_oci/issues/430
I think it would be nice if `oci_register_toolchains` configured this, but I understand not wanting to clutter the configs.
To test:
WORKSPACE:
```
local_repository(
name = "rules_oci",
path = "/local/rules_oci",
)
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@rules_oci//oci:dependencies.bzl", "rules_oci_dependencies")
rules_oci_dependencies()
load("@rules_oci//oci:repositories.bzl", "LATEST_CRANE_VERSION", "oci_register_toolchains")
oci_register_toolchains(
name = "oci",
crane_version = LATEST_CRANE_VERSION,
) …
```

support passing label as container cli tool to bazel run //my/tarball

---

README.md

A lot of people seem to make the assumption that this is a 1:1 replacement for rules_docker.

docs: clarify rules_docker replacement belief

---

MODULE.bazel
oci/private/image.bzl
oci/private/versions.bzl

Bumping the version of `crane` to 0.18.0 so that full image references are always printed to stdout for downstream `oci_push` consumers to use (https://bazelbuild.slack.com/archives/CA3NW13MH/p1705512905768289).
Buildifer automatically formatted some additional bits, can manually revert those if needed.

feat: bump and assert crane version 0.18.0

---

fetch.bzl
oci/private/pull.bzl
oci/tests/BUILD.bazel

Allows oci_pull from private quay.io repositories.
Follows https://github.com/bazel-contrib/rules_oci/pull/471

Add quay.io registry support

---

oci/pull.bzl

Allow overriding the config path for this macro.

Fix config_path not passed through in oci_pull macro

---

.github/workflows/ci.yaml
.github/workflows/release.yml
internal_deps.bzl
oci/dependencies.bzl

Just some minor cleanup make this repository consistent with all our other OSS repos.
- maybe pattern doesn't use name elsewehre
- update to actions/checkout@v4
- use correct pattern for GHA PR concurrency
- update to bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v5
- remove the big WARNING from rules_oci_dependencies; this doesn't exist in our other repos anymore

chore: repository cleanup

---

oci/private/registry/crane_launcher.sh.tpl

https://github.com/google/go-containerregistry/pull/1810 introduced this feature where blobs are written to `disk_path/hex/digest` but rules_oci assumed that it was `disk_path/blobs/hex/digest` so blobs were written to the wrong place..

fix: blob directory is wrong

---

oci/private/image.sh.tpl

Reverts bazel-contrib/rules_oci#490
In some client testing, this breaks the build. I think `crane push` actually does exit non-zero in the happy path case.

Revert "fix: improve error reporting"

---

oci/private/util.bzl

rctx.execute will not return 127 if shasum is not found on a linux machine; you'll just get an error code of 1 when that happens

fix: fix util.sha256 error code handling

---

examples/env_inheritance/BUILD.bazel
examples/env_inheritance/test.yaml
oci/private/image.sh

If base image contained a variable  `BASE_VAR=key=value` and one would set `MY_VAR=$BASE_VAR additional value` the `MY_VAR` would be set to `key additional value`
Fixing this by parsing `config.Env` elements as:
1. variable name - string up to first "="
2. variable value - whole string after first "="

Support inheriting environment variable that's value contains =

---

oci/private/image_index.sh.tpl

Reverts bazel-contrib/rules_oci#359
Context: users started seeing cryptic errors which i believe started with this commit. Will confirm that it's the case.
I have no idea why i merged this but up until 7.1 bazel did not support symlinks inside treeartifacts pointing out of it.

Revert "feat: use link instead of copy for blobs in oci_image_index"

---

oci/private/image.bzl

Reverts bazel-contrib/rules_oci#523
not actually supported by underlying crane

Revert "image: allow .tar.zst extension on layer tar"

---

cosign/private/versions.bzl

fixes #535 
In addition I think older releases of cosign that depend on the TUF repository should be removed cc: @haydentherapper

Add cosign v2.2.3

---

docs/push.md
examples/env/BUILD.bazel
examples/labels/BUILD.bazel
examples/push/BUILD.bazel
oci/private/push.bzl

Also include the aspect_bazel_lib load statement since the bazel_skylib one is broken. Fixes #512

docs: simplify use of expand_template

---

.github/workflows/ci.yaml
MODULE.bazel
WORKSPACE
internal_deps.bzl

Removes unused rules_js dependency. 
Prefactor for #533

chore: upgrade rules_go and gazelle

---

docs/push.md
oci/private/push.bzl

The `name` attribute is required but wasn't defined in the examples

[docs] Add missing name to push examples

---

fetch.bzl
oci/private/authn.bzl
oci/tests/BUILD.bazel

I reported the issue at https://github.com/bazel-contrib/rules_oci/issues/475#issuecomment-1960581407 that `oci_pull` fails to download images from nvcr.io. As suggested in the comment at https://github.com/bazel-contrib/rules_oci/issues/284#issuecomment-1692815824, I added a new entry for nvcr.io to `_WWW_AUTH`. I locally applied the patch and confirmed that `oci_pull` successfully downloaded images which were previously failed.
I took the values from the information provided at https://forums.developer.nvidia.com/t/how-to-get-manifest-from-nvcr-io-docker-registry-using-rest-api/72385/2

feat: add nvcr.io to _WWW_AUTH

---

oci/private/authn.bzl

Looks like the quay config got lost when refactoring `pull.bzl` to `authn.bzl` this PR adds it back

fix: Add quay back to authn config 

---

.github/workflows/ci.yaml
MODULE.bazel
WORKSPACE
cosign/private/attest.bzl
cosign/private/attest.sh.tpl
cosign/private/sign.bzl
cosign/private/sign.sh.tpl
e2e/convert_docker_tarball/WORKSPACE
e2e/crane_as_registry/WORKSPACE.bazel
e2e/custom_registry/WORKSPACE
e2e/smoke/MODULE.bazel
e2e/smoke/WORKSPACE.bazel
examples/multi_arch/BUILD.bazel
examples/multi_arch_go/BUILD
internal_deps.bzl
oci/dependencies.bzl
oci/private/image_index.bzl
oci/private/image_index.sh.tpl
oci/private/push.bzl
oci/private/push.sh.tpl
oci/private/tarball.bzl
oci/private/tarball.sh.tpl
oci/repositories.bzl

Fixes #384. blocked on bazel-lib 2.0

refactor: remove yq dependency

---

oci/private/tarball.bzl
oci/private/tarball.sh.tpl
oci/repositories.bzl

Note, this shouldn't land until bazel-lib 2.0 is stable (RC or ideally final)

refactor: use hermetic tar

---

oci/private/image.bzl
oci/private/image_index.bzl
oci/private/tarball.bzl

This is a step forward for the migration of Automatic Exec Groups. These actions don't use an executable/tool from a toolchain. Hence, `None` should be set.

Add `toolchain` param to the affected actions

---

oci/BUILD.bazel
oci/private/download.bzl
oci/private/pull.bzl

As of Bazel 7.1, it is possible to pass arbitrary headers to the Bazel downloader. Combined with proper credentials, this change makes it possible to avoid the cURL fallback on 7.1+.
It feels weird to pass the same headers to every invocation of `_download()`. Should we move `_SUPPORTED_MEDIA_TYPES` and `_DOWNLOAD_HEADERS` somewhere they could be imported in `download.bzl`?

Pass headers to Bazel downloader where available

---

docs/cpp.md

docker.io/library/ubuntu contains required toolchain. GCR is no longer maintained and is shutting down [link](https://cloud.google.com/artifact-registry/docs/transition/prepare-gcr-shutdown?_gl=1*tkwscz*_ga*MTE3Njk2NzAxMy4xNzA4ODQ1NjQw*_ga_WH2QY8WWF5*MTcxNDk0MTI5My43OC4xLjE3MTQ5NDEzMDAuMC4wLjA.&_ga=2.246388676.-1176967013.1708845640&_gac=1.253163003.1714817497.Cj0KCQjwudexBhDKARIsAI-GWYVhO6QleeFT7rzyBWZvb2pi9bksKKOkNxgd826LvJNFz3D2oSZ4LasaAujoEALw_wcB), so that's another reason for this doc update.

Fix #552 and update readme

---

.github/workflows/ci.bazelrc
.github/workflows/ci.yaml

The --disk_cache flag produces large outputs and causes flaky CI when we run out of disk.

Reduce GHA caching

---

MODULE.bazel
oci/dependencies.bzl
oci/private/BUILD.bazel
oci/private/image.bzl
oci/private/image.sh
oci/repositories.bzl

fixes https://github.com/bazel-contrib/rules_oci/issues/508, needs https://github.com/bazel-contrib/rules_oci/pull/558 first.

feat: implement tars symlinks

---

oci/private/authn.bzl

This pull request update authn.bzl to create a bat script on Windows to fix "%1 is not a valid Win32 application" (fixes #555).

Fix oci_image failing with "%1 is not a valid Win32 application"

---

examples/big_image/BUILD.bazel
oci/private/image.bzl
oci/private/image.sh

feat: support symlinking blobs from base

---

examples/deb/BUILD.bazel
fetch.bzl
oci/private/image.sh

In 2.x, tars stopped being direct inputs `OCIImage` actions, this meant that none of the tars passed by the user actually went into the sandbox.  fixes #566 
Imagine an oci_image in `examples/env/image` 
`bazel-out/darwin_arm64-fastbuild/bin/external/bash_amd64/data.tar.zst`  -> did fail because `external` segment does not exist, therefore can't be canonicalized.
`bazel-out/darwin_arm64-fastbuild/bin/examples/env/image/data.tar.zst` -> did NOT fail because all components in the path except the file itself existed, therefore can be canonicalized.
In the scenario above `realpath` failed if any of the directory segments in the path was missing leading to errors only when external repository labels passed to tars.  This fixes the issue by telling `realpath` to ignore missing segments, and we …

fix: canonicalize missing components

---

oci/private/BUILD.bazel
oci/private/push.bzl
oci/private/util.bzl

This pull request updates `util#_maybe_wrap_launcher_for_windows` to use relative paths to fix `bazel run` failing on Windows with `/usr/bin/bash: line 1: bazel-out/x64_windows-fastbuild/bin/some-project/push_app-image-push.sh: No such file or directory`
and update push.bzl to use `util#maybe_wrap_launcher_for_windows` (fixes #564)

oci_push to support Windows builds

---

oci/private/tarball.sh.tpl

Hello,
I've noticed that in my case following build description:
```
oci_image(
name = "img-amd64",
base = "@eclipse_temurin_17_linux_amd64",
tars = [
":app-tar"
],
)
oci_image(
name = "img-arm64",
base = "@eclipse_temurin_17_linux_arm64_v8",
tars = [
":app-tar"
],
)
oci_image_index(
name = "img-multiarch",
images = [
":img-arm64",
":img-amd64"
]
)
oci_tarball(
name = "img-tarball",
format = "oci",
image = ":img-multiarch",
repo_tags = ["some-name:latest"],
)
```
was causing following error:
```
bazel run //:img-tarball
INFO: Invocation ID: 61c8d196-44e6-4e78-8d80-d2b9c23f29e0
INFO: Analyzed target //:img-tarball (33 packages loaded, 291 targets configured).
INFO: Found 1 target...
ERROR: BUILD.bazel:179:12: OCI Tarball //:img-tarball failed: (Exit 1): tarball.sh failed: error executing …
```

Quotes removal from MEDIA_TYPE string.

---

oci/extensions.bzl

Return extension_metadata from oci.pull(), making `bazel mod tidy` automagically populate `use_repo(oci, ...)` in MODULE.bazel
Fixes https://github.com/bazel-contrib/rules_oci/issues/529

Return extension_metadata from oci.pull()

---

examples/test1/BUILD
examples/test2/BUILD

Run:
```
bazel build //examples/test2:extended
```
Basing on examples/big_image, but separated into two BUILD files to invoke path errors.

Reproducing image creation errors

---

examples/assertion/BUILD.bazel
examples/assertion/README.md
examples/big_image/README.md
examples/just_tar/BUILD.bazel
examples/just_tar/README.md
examples/simple/README.md
examples/various/BUILD.bazel
oci/private/image.sh
oci/private/push.bzl

When a blob exists already, there's no reason to try to relink or copy it to the output folder.  See: https://github.com/bazel-contrib/rules_oci/issues/566#issuecomment-2106839723
fixes #566

fix: duplicate tar copying

---

MODULE.bazel

As `jq` is required for `oci_push` in https://github.com/bazel-contrib/rules_oci/blob/d49f7b6cfee40179d8accf420ec219cb874c040e/oci/private/push.bzl#L139 mark it as such.
This was probably overlooked in #386.

Add jq as dependency required for oci_push

---

oci/private/pull.bzl

I captured this going wrong with traces in our internal repository.
A. debian_golden_linux_amd64
B. debian_golden_linux_arm64_v8
1. `manifest, size, digest = downloader.download_manifest(rctx.attr.identifier, "manifest.json")`
_traces_
```
(01:43:56) DEBUG: /mnt/ephemeral/output/__main__/external/rules_oci/oci/private/pull.bzl:108:10: debian_golden_linux_amd64 downloading https://index.docker.io/v2/library/debian/manifests/sha256:432f545c6ba13b79e2681f4cc4858788b0ab099fc1cca799cc0fae4687c69070 with sha256 432f545c6ba13b79e2681f4cc4858788b0ab099fc1cca799cc0fae4687c69070
```
2. the download manifest is parsed and found to be an image index manifest, the platform is looked up in the index and the following download is started: `manifest, size, digest = …

fix: fix race condition in oci_pull where bazel can write platform manifest contents to the cache entry for image index manifest

---

oci/private/push.sh.tpl

Same as https://github.com/bazel-contrib/rules_oci/pull/577
Without this flag, I get the following error while running push target:
```
Error: could not parse reference: <redacted>@"sha256:64f4e09cc1516853175ec87b0fde29673b99864262a82bd0eac5b1faaa46ef3b"
```

--unwrapScalar for yq cmd

---

MODULE.bazel
oci/private/push.bzl

Bazel doesn't provide a very elegant way to specify that a toolchain should be resolved in such a way that it can be executed on a *target* platform:
https://github.com/bazelbuild/bazel/issues/19645
To work around this, we can pass in the toolchains through ordinary labels and apply an outgoing edge transition to set --extra_execution_platforms equal to --platforms. This causes the toolchains to be resolved the way we want.
Though I think using transitions for this is pretty slick, it's a shame that this has to be done by patching up command line options.

Use a transition to resolve the correct versions of crane and yq

---

oci/private/pull.bzl

Re-created after https://github.com/bazel-contrib/rules_oci/pull/582 was accidentally closed.
cc:@thesayyn

Use non-blocking download to get image blobs, on Bazel >=7.1.0

---

oci/private/image.bzl

In 2.0, we promised that `tars` were no longer directly inputs to oci_image, but it was never possible to do it because of subtle ways of how bazel works. Even though it worked with most execution strategies, it did not work with RBE and BwoB because of how bazel calculates hashes for treeartifacts. 
Discussion here: https://github.com/bazelbuild/bazel/issues/22504

   fix: add tars into action inputs

---

.github/workflows/ci.yaml
examples/dockerfile/BUILD.bazel

This example required a bit of preconfiguration in CI settings, but the release pipeline uses a composite ruleset from bazel-contrib so we can't change it.  Disabling the examples/dockerfile for now.

chore: disable dockerfile example

---

e2e/smoke/MODULE.bazel
oci/extensions.bzl

fixes https://github.com/bazel-contrib/rules_oci/issues/529 https://github.com/bazel-contrib/rules_oci/issues/610

fix: return correct extension metadata

---

examples/assertion/BUILD.bazel
oci/private/tarball.bzl
oci/private/tarball.sh.tpl
oci/private/tarball_run.sh.tpl

A while back we changed oci_tarball for performance reasons, and we introduced two different ways to load tarball into the daemon, one where one run `bazel run :tarball_target` or `bazel build :tarball_target --output_groups=tarball && docker load -i tarball.path` or directly get the output in DAG. 
So in order to support all these cases we introduced some hacks like using `--cd` option to cd back into the execroot and strip the paths using `<ctx.bin_dir.path>`. 
Unfortunately this did not work for cases where bindir of oci_tarball and oci_image is disjoint, eg oci_image is transitioned but oci_tarball isn't simply because the assumption that everything is in the same `bazel-bin/cfg/bin` did not hold true in cases above. 
This PR fixes it by making eveything relative to execroot, which …

fix: make oci_tarball work with disjoint output root

---

docs/pull.md
oci/private/pull.bzl
oci/pull.bzl

Adds an import_tags attribute to the oci_pull macro to allow passing Bazel tags to the underlying rules. This implementation follows the naming and general implementation of the import_tags attribute on the old legacy container_pull rule.
#572

Add import_tags attribute to oci_pull

---

oci/private/image.sh
oci/private/image_index.sh.tpl

Unlike `cat` redirected to a file, `cp` sees both its input and output and can more readily know the details of its arguments. These details can sometimes be exploited to achieve zero-copy transfers when the OS and filesystem know how to do copy-on-write (e.g. `clonefile` on Mac, `copy_file_range` on Linux). uutils' `cp` will attempt to take advantage of these opportunities where possible (see: https://github.com/uutils/coreutils/blob/35232689366fb102854693b6bd6b6161901d192e/src/uu/cp/src/cp.rs#L2190 ).
We need to pass `--no-preserve=mode` in order for `cp` to create the files as writable; which is necessary as some of the copies we perform need to be mutated afterwards. Depending on the nature of the Bazel setup, action input files might be readable but not writable, so the default …

Copy files using coreutils cp

---

oci/private/image.sh

This error also occurs when a file with labels ends with an EOL character.
Fix #613

Fix `jq: error (at <stdin>:16): Cannot use null (null) as object key` error on empty line in labels file

---

e2e/pull/test.bats
oci/private/authn.bzl

It is perfectly normal to have config.json with just the global config store:
{ "credsStore": "osxkeychain" }
See https://github.com/docker/docker-credential-helpers?tab=readme-ov-file#usage and https://github.com/google/go-containerregistry/tree/main/pkg/authn#helpers for examples.
Previously, the authn-code would only look at the `credsStore` if there was a specific host maching in `auths`, but lacking other authn-fields.
Now it also looks at the global `credsStore` as a fallback.
Fixes #388.

fix: Support global credsStore in docker config

---

examples/BUILD.bazel
examples/assertion/BUILD.bazel
examples/assertion/assert.bzl
fetch.bzl
oci/private/image.sh

This fixes a bug where oci_image removed the content of env variables after first `=` in the value.  This fixes that issue and adds more tests to test against other cases. 
I added a nice assertion rule similar to `assert_tar_contains` which doesn't depend on a docker daemon and doesn't require a yaml file as a configuration language.
(it was already somewhere in a branch, i just added it here so i can use it in the future.)

    fix: env vars containing =

---

.github/workflows/ci.yaml
examples/assert.bzl
examples/assertion/BUILD.bazel
oci/private/BUILD.bazel
oci/private/tarball.bzl
oci/private/tarball_run.sh.tpl

Fixes an issue where tarball does not work when a genrule/sh_test runs it.

fix: make oci_tarball work with genrule

---

oci/private/image.sh

When building OCI images, we use a newline separated file in the form "a=b\nb=c\nd=e". However, if this file has a trailing newline, you get a pretty confusing error like "jq: error (at <stdin>:37): Cannot use null (null) as object key" because jq splits that final newline into an empty string, and further tries to split it on the "=" which results in a null key.
Instead, filter out any empty strings.

fix: Ignore empty annotations in the jq query

---

examples/assertion/BUILD.bazel
oci/private/tarball_run.sh.tpl

Adds a test for oci_tarball to assert that it can be used as part of an sh_test target.  
Fixes an issue where RUNFILES_DIR env is not exported when running the tarball target.

 test: add oci_tarball test for sh_test

---

docs/scala.md

To make life easier for people who come from rules_docker and use scala, I documented basic setup. I based it on docs for java and rust.

Document how to use rules_oci with scala

---

docs/compare_dockerfile.md
docs/image.md
examples/assert.bzl
examples/assertion/BUILD.bazel
oci/defs.bzl
oci/private/image.bzl
oci/private/image.sh

feat: add support for settings volumes

---

examples/multi_architecture_image/BUILD.bazel
oci/private/image_index.sh.tpl

In the recent bazel-contrib/rules_oci#386, when we replaced use of the _yq_ tool with the _jq_ tool, we [translated the `oci_image_index` rule's accumulation of image manifests incorrectly](https://github.com/bazel-contrib/rules_oci/pull/386/files#r1646778569), such that we lose all but the last index that we add to the index.
In `jq`, [the _update-assignment_ operator](https://jqlang.github.io/jq/manual/#update-assignment) (`|=`) does not append to an array supplied as its left-hand context value automatically. Instead, one must use [a _complex assignment_](https://jqlang.github.io/jq/manual/#complex-assignments), mentioning the context value explicitly together with [the addition operator](https://jqlang.github.io/jq/manual/#addition).
See [the preceding discussion in the "docker" …

fix: accumulate image manifests in oci_image_index

---

oci/private/load.bzl
oci/private/tarball.sh.tpl

Updates `tarball.sh.tpl` to use the hermetic coreutils.  I opted to match the existing script form of supplying a variable for the executable instead of the newer `image.sh.tpl` form of modifying `PATH` and assuming the binary name (particularly as updating `tar` doesn't seem like it would work as the binary name is different between Windows and Unix).  If you'd prefer I modify `PATH` to find `coreutils`, I could do that instead.

tarball uses hermetic coreutils

---

e2e/pull/wksp/BUILD.bazel
e2e/pull/wksp/MODULE.bazel
oci/private/pull.bzl

This makes the external image repos also expose the digest file, similarly how
the `oci_image` creates a `.digest` target. The actual name of the file can be
something else and I am just putting this out to initiate a discussion.
Let's say a user has `@alpine` image defined via `oci_pull`, they can access the
digest of the upstream image by accessing the `@alpine//:image.digest` file.
We could similarly have the platforms of the image written to a file as well,
but I am not sure if that is useful.
Having the `image.digest` in a file could be useful for various automation that
is done using `write_source_file` rule where one would use a `genrule` to get
the `digest` value from the `@alpine//:image.digest` target, transform it and
output it to a file that is later synced with …

feat(oci_pull): expose the digest as a file

---

cosign/private/attest.bzl
cosign/private/sign.bzl
examples/assertion/BUILD.bazel
examples/assertion/assert_push_transitive_deps.sh
oci/private/image.bzl
oci/private/load.bzl
oci/private/push.bzl

This has surfaced as bug in most of the places like https://github.com/bazel-contrib/rules_oci/issues/643, https://github.com/bazel-contrib/rules_oci/issues/642 (most likely). 
The problem was that when symlinks were enabled on Bazel 7, the logic did not propagate the file dependencies correctly downstream which lead to some obscure errors i have mentioned above. 
Now that we have some provider hierarchy, it makes me think if we should have a provider here, as requested in:  https://github.com/bazel-contrib/rules_oci/issues/279

fix: propagate transitive inputs

---

oci/private/authn.bzl
oci/private/util.bzl

Due to inactivity, I picked up this PR: https://github.com/bazel-contrib/rules_oci/pull/581
I implememented the mentioned workarounds, i.e. in case of windows, I try to run script using powershell, otherwise, I fallback to curl and then wget, both wrapped in a bash script.
I tested these with an azure repo which requires oauth2. I also tested it on windows. I found that the config.json is not found due to "stat" binary not existing on windows, so I fixed this too.

Oauth2 support without Python

---

e2e/assertion/wksp/MODULE.bazel
e2e/assertion/wksp/WORKSPACE
examples/assert.bzl
examples/assertion/BUILD.bazel
oci/private/image.sh

This is a follow-up to https://github.com/bazel-contrib/rules_oci/pull/654 for consistency. 
Also fixes an old issue: https://github.com/bazel-contrib/rules_oci/issues/438

fix: set created property for scratch base

---

e2e/assertion/wksp/MODULE.bazel
e2e/assertion/wksp/WORKSPACE
examples/assert.bzl
examples/assertion/BUILD.bazel
examples/multi_architecture_image/BUILD.bazel
oci/private/descriptor.sh
oci/private/image.bzl
oci/private/image.sh

image-spec says that this field is optional, however some systems like seen in https://github.com/bazel-contrib/rules_oci/issues/645 require this field. Also, skipping history entries lead to broken images if the base image already had one. 
fixes https://github.com/bazel-contrib/rules_oci/issues/645

fix: add history entries for tars attribute

---

oci/private/load.sh.tpl

Currently the generated template looks like
```bash
if [ -e "$LOADER}" ]; then
CONTAINER_CLI="$LOADER"
elif command -v docker &> /dev/null; then
CONTAINER_CLI="docker"
```
This will never evaluate the first if clause, because `$LOADER}` will for an empty `LOADER` expand to `}`.

fix typo in load.sh.tpl

---

examples/assertion/BUILD.bazel

Turns out we fixed this accidentially when we implemented support for stamping of `entrypoint` and `cmd`. 
Closes https://github.com/bazel-contrib/rules_oci/issues/336

test: add test for setting entrypoint to []

---

examples/dockerfile/buildx.bzl

Ensures that buildx builder gets recreated
Reproduced the issue in GitHub Actions with cache of repositories and external dependencies. The issue:
```
ERROR: /home/runner/work/xxx/BUILD.bazel:16:11: BuildDocker xxx/base failed: (Exit 1): buildx failed: error executing BuildDocker command (from target //xxx:base) bazel-out/k8-opt-exec-ST-a828a81199fe/bin/xxx/buildx build xxx --builder builder-docker ... (remaining 1 argument skipped)
ERROR: no builder "builder-docker" found
```
The fix is based on the following doc statement: https://arc.net/l/quote/fxyvuetr
PS. I am not an expert in bazel and my fix may be incorrect. I am welcome to a different solution

fix: ensures confugure_buildx rule runs when bazel server restarts

---

oci/private/push.sh.tpl

There's two things here:
When passing `-v` or `--verbose` to the push, it only propagates to the first crane command. This adds it to the tag pushes as well to help with debugging.
When the tags file is empty, GNU xargs was causing a failure. This is because [GNU xargs](https://www.gnu.org/software/findutils/manual/html_node/find_html/xargs-options.html) executes the command once even if the input is empty, so `crane` was raising an exception about the wrong number of arguments. Passing `-r` will give xargs the same behavior as BSD xargs. in BSD xargs, `-r` is a no-op.

Fix for gnu xargs and send --verbose to other commands

---

oci/extensions.bzl

I think this should be all that's needed to fix https://github.com/bazel-contrib/rules_oci/issues/686

Allow bazel_tags in bzlmod extension (fixes #686)

---

docs/pull.md
oci/pull.bzl

The documentation only had `WORKSPACE.bazel` examples, so I'm adding one for `MODULE.bazel`.
The example I'm using also has a slight "issue" with the architecture variant that (I think) can easily to trip people (like it tripped me).

Add Blzmod example to pull.md

---

oci/private/load.bzl

BREAKING CHANGE:
It's unfortunate that we make a breaking change in an RC phase, but we haven't seen anybody using this output so far. 
Removal of the mtree as the default output allows `$(location :oci_load_label)` to return the `executable` instead of the `DefaultInfo.files[0]` which what most expect.

refactor: remove mtree as the default output

---

docs/rust.md

the release notes [here](https://github.com/bazel-contrib/rules_oci/releases/tag/v2.0.0) recommend adding extension to use compression

use compression in examples

---

docs/load.md
oci/private/load.bzl

For people upgrading from earlier versions of rules_oci, it works out better to use `+tarball` than `tarball`. With the docs as currently written, without the plus sign, it will break for anyone using an earlier version of rules_oci. Adding the plus makes it work with either older or newer versions of rules_oci, which is convenient for people who are upgrading incrementally.
It's probably a good habit, anyway, to use the plus. When you want an extra output group to a build, you usually don't want to cancel all the output groups you don't know about. You just want to add the one new one that you do care about.

Add a plus sign to the output_groups option

---

docs/push.md
oci/private/push.bzl

`oci_push#remote_tags` is too restrictive about what the file extension should even thought it doesn't really care what it is as long as it is a valid text file.

refactor: remote_tags unnecessarily restrictive

---

docs/image.md
oci/defs.bzl

Fixes bazel-contrib/rules_oci#698

doc: cover the inline-specified variants of arguments to oci_image

---

e2e/smoke/.bazelrc

https://github.com/bazel-contrib/rules_oci/actions/runs/11564798863/job/32190695142
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
In #724 it looks like I broke macos CI because that particular step is not run as part of the PR builds. I introduced a genrule which requires access to the docker daemon, while previously it was only used in test rules.
Adding the env var to the docker host to the action graph should maybe fix this?

Fix macOS CI after #724

---

cosign/repositories.bzl

Adding this flag to make it possible to use in bzlmod. This approach aligns with https://github.com/bazel-contrib/rules_oci/blob/a195e365b8653139bef7f6bbb3e7b00b4eabd024/oci/repositories.bzl#L97

feat: Possible to skip cosign toolchains registration

---

.bazelrc
.bazelversion
.github/workflows/ci.yaml
oci/private/versions.bzl
oci/repositories.bzl

Note, I would have added the `--incompatible_use_plus_in_repo_names` flag to `.bazelrc` in this PR, but that would break our Bazel 6 test matrix. We'll get that flag soon enough when we add Bazel 8 testing.
Fixes #738

chore: upgrade regctl

---

.github/workflows/release.yml
.github/workflows/tag.yaml
CONTRIBUTING.md

Simplifies life for maintainers a bit, ensuring we're never more than two weeks without commits getting shipped.
Downstreams https://github.com/bazel-contrib/rules-template/pull/129

chore(cd): automate release tagging

---

docs/BUILD.bazel
docs/image_index.md
examples/multi_architecture_image/BUILD.bazel
oci/defs.bzl

Related issue #735.
Since `oci_image_index` was a rule directly exposed in `defs.bzl`, I had to introduce a new macro. I opted to make it in the same way as `oci_index`, by using the `oci_index_image` name for the macro, while renaming the existing rule as `oci_index_image_rule`. I'm not sure if this kind of change would be considered a breaking change or not.
Please review if you find this kind of change from a rule to a macro acceptable or not. If not, I can expose this new macro with a different name (if you have any suggestions on what name to use, I'm all ears 😅) keeping the old rule unchanged.

feat: Transition oci_image_index into a macro with additional [name].digest target

---

oci/defs.bzl

Symbolic macros require labels to start with their own name, so if you have a symbolic macro wrapping one of the OCI legacy macros, it will fail. Adjust the names to satisfy this new requirement.
See https://bazel.build/extending/macros#naming, these naming conventions are violated by this legacy macro (and thus by a symbolic macro wrapping this legacy macro)

Fix compatibilty with symbolic macros

---

oci/private/image.sh

The [OCI spec](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#properties) provides a `data` field in order to embed a copy of an image's config directly into that image's manifest:
> data string
>
> This OPTIONAL property contains an embedded representation of the referenced content. Values MUST conform to the Base 64 encoding, as defined in RFC 4648. The decoded data MUST be identical to the referenced content and SHOULD be verified against the digest and size fields by content consumers. See Embedded Content for when this is appropriate.
This is [intended as an optimization](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#embedded-content), in order to reduce the number of network round-trips incurred to pull a container from a remote …

fix: drop embedded config data from manifest image

---

examples/dockerfile/buildx.bzl

We've been using https://github.com/bazel-contrib/rules_oci/tree/main/examples/dockerfile for a while now and its been working well.
In our repo, I added another rule that also needed to use the `buildx` binary, but it seems that the rule has a race condition. This wasn't happening on my Mac but it was happening in our CI machines running on Linux.
Example error:
```
#0 building with "builder-docker" instance using docker-container driver00:27
#1 [internal] booting buildkit00:27
#1 pulling image moby/buildkit:buildx-stable-100:27
#1 pulling image moby/buildkit:buildx-stable-1 5.4s done00:27
#1 creating container buildx_buildkit_builder-docker000:27
#1 creating container buildx_buildkit_builder-docker0 14.4s done00:27
#1 ERROR: Error response from daemon: No such container: …
```

Add --use --bootstrap to dockerfile builder example

---

docs/pull.md
oci/private/authn.bzl
oci/pull.bzl

Introduces the OCI_GET_TOKEN_ALLOW_FAIL repo env.
If set, the builtin credential handling will be allowed to fail and a credential helper can be used instead.
Fixes #760

authn: allow builtin credential handling to fail conditionally

---

oci/private/authn.bzl

Avoid leaking tokens during `bazel vendor`.

authn.bzl: Delete www-authenticate.json after use

---

.bazelignore
.github/workflows/ci.yaml
examples/dockerfile/BUILD.bazel
examples/dockerfile/Dockerfile
examples/dockerfile/MODULE.bazel
examples/dockerfile/README.md
examples/dockerfile/bins/hi/BUILD.bazel
examples/dockerfile/bins/hi/main.go
examples/dockerfile/buildx.bzl
examples/dockerfile/libs/lib1/BUILD.bazel
examples/dockerfile/libs/lib1/lib.py
fetch.bzl

For a long time we had dockerfile example but its DX was never good, this updates our  examples/dockerfile to be standalone and publishes the api with better DX that we created for somebody else.

refactor: publish better buildx api

---

examples/tarball_as_base/BUILD.bazel

Adds an example for using a docker tarball as a base image to oci_image. In 1.x version of rules_oci this worked by accident where passing a tarball to the base attribute of oci_image would extract the tarball and use it as the base image but in 2.x this stopped working because we actually started asserting that the base image was in fact an oci-layout. 
Users are required to register the regctl toolchain in their MODULE.bazel if bzlmod is in use. 
```
oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.toolchains()
use_repo(oci, "oci_regctl_toolchains")
```
Closes https://github.com/bazel-contrib/rules_oci/issues/700

example: use docker tarball as base image

---

oci/private/image_index.sh.tpl

`dirname` is part of `coreutils` and may be unavailable on remote executors environments, let's use hermetic version

image_index.sh.tpl: use "dirname" from COREUTILS

---

.github/workflows/publish.yaml
.github/workflows/release.yml

Now it's a reusable workflow and includes provenence attestations for release artifacts

chore: use new Publish-to-BCR

---

cosign/BUILD.bazel

The cosign/defs.bzl also [depends on attest.bzl](https://github.com/bazel-contrib/rules_oci/blob/main/cosign/defs.bzl#L3). I suppose this dependency should be declared in bzl library.

Add missing dependency to //cosign:defs

---

docs/migrate_from_rules_docker.md

We want that site to be just for our workflows product going forward. Most users have finished this migration already.

chore: move migration guide from aspect docsite.

---

docs/static_content.md

Removed the leading slash of the `package_dir` to avoid running into bazel-contrib/bazel-lib#1031.

Fix static content example

---

oci/extensions.bzl
oci/pull.bzl

The `oci_pull` rule supports `registry` and `repository` attributes
but the `oci.pull` tag class did not provide them.
This commit adds the `registry` and `repository` attributes
to `oci.pull`, and forwards them to the `oci_pull` rule.
Resolves #732

feat(oci.pull): support registry and repository attributes

---

docs/push.md
examples/push/BUILD.bazel
examples/push/test.bash
examples/push/test_push_image_wo_repository_fails.bash
oci/private/push.bzl
oci/private/push.sh.tpl

This makes the `repository` and `repository_file` attributes of the `oci_push` rule optional. If neither is specified, the repository must be provided at runtime via the `--repository` flag.
This allows for more flexible usage of the `oci_push` rule, where the repository is not known at build time, for example in tutorials and examples.

feat(oci): make repository attribute optional in oci_push (#822)

---

cosign/private/attest.bzl
cosign/private/attest.sh.tpl
cosign/private/sign.bzl
cosign/private/sign.sh.tpl
examples/attest/BUILD.bazel
examples/attest/test_attest_no_repo_fails.bash
examples/attest/test_attest_no_repo_passes.bash
examples/sign/BUILD.bazel
examples/sign/test_sign_no_repo_fails.bash
examples/sign/test_sign_no_repo_passes.bash

This makes the `repository` attribute of the `cosign_sign` and `cosign_attest` rules optional. If not specified, the repository must be provided at runtime via the `--repository` flag.
This allows for more flexible usage of the cosign rules, where the repository is not known at build time. This is useful for example in cases where the code is being provided as an example or a codelab.

feat(cosign): make repository attribute optional in cosign rules

---

oci/private/load.bzl

Before: only single executable "file" was allowed as loader for `oci_load`
After: loader can still be single file, but also can be arbitrary executtable target
`allow_single_file` -> `allow_files` change is necessary to support loaders with runfiles

oci_load: allow loader to be a target label

---

oci/private/authn.bzl

When OCI_GET_TOKEN_ALLOW_FAIL is enabled, allow the credsStore and credHelpers from the Docker config file to fail silently.
This prevents local Docker config files from breaking pulls when rules_oci is configured to allow the built-in credential management to fail.
Fixes #816

fix: Allow credsStore and credHelpers to fail in some cases
